spring:
  application:
    name: spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9070
  boot:
    admin:
      client:
        url: http://localhost:9090
server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/