spring:
  application:
    name: spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9070
  boot:
    admin:
      client:
        url: http://localhost:9090
server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/