spring:
  application:
    name: spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:9090
server:
  port: 9070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false